### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by Tuvqlu** [cosmicnebula200/FunBlockLuckyBlock#1]
Hey this plugin sounds pretty cool, available for download?

**Comment by cosmicnebula200** [comment]
> Hey this plugin sounds pretty cool, available for download? 

Hey @Tuvqlu ,

This plugin isnt ready for production yet. Once it is ready it will be submitted on poggit.

**Comment by Tuvqlu** [comment]
Ohhh that makes so much sense lol, good luck!
